### ISSUE TITLE
Error: (dbus-error "Emacs not compiled with dbus support")

### ISSUE THREAD

**Issue by jueqingsizhe66** [wztdream/org-clock-watch#1]
# 1. Running environment
1.  Windows 10 + Emacs27.1
2. org 9.4.6
3. org-clock-watch(2021-07-06)
4. mplayer.exe for play music

# 2. Problem
1. `M-x org-clock-watch-status `  ---> "it is running "
2. After 3minutes, emacs send the noise "why not clock in" , everything works on!
3. However, `Error: (dbus-error "Emacs not compiled with dbus support")` in the minibuffer and emacs cannot be operated any more, 

- emacs was playing the ding.wav without stop , she said: "ding ding ding...."
- `Ctrl-g` not working, keyboard and mouse not  working , only by force kill the emacs app!

Restart the emacs, and problem can be reproduced .

![lock](https://user-images.githubusercontent.com/1592836/124614540-ebfb8980-dea6-11eb-9e4e-7c19e34790c3.png)

# 3. Solution
no.

**Comment by wztdream** [comment]
>     However, Error: (dbus-error "Emacs not compiled with dbus support") in the minibuffer and emacs cannot be operated any more,
The error means your emacs do not have the capability of dbus, and `org-clock-watch` uses `notifications-notify` which need dbus. So the solution is that you need to install emacs that compiled with dbus support. I do not use windows, so you have to do some homework to install it.
org-clock-watch use 'notifications-notify` to send the alarm, here is related document in Elisp info:
```
Emacs is able to send “notifications” on systems that support the
freedesktop.org Desktop Notifications Specification and on MS-Windows.
In order to use this functionality on POSIX hosts, Emacs must have been
compiled with D-Bus support, and the ‘notifications’ library must be
loaded. ....

```
> 
>     emacs was playing the ding.wav without stop , she said: "ding ding ding...."
This is the micro rest alarm, which alarm you to take a very short rest, 1 min or 10 second etc, I will change the default value to off, as this is not a common use case.
you can enable or disable it and modify the interval and sound by customizaiton:
```
Org Clock Watch Micro Rest Interval 
   micro rest means a very short time interval and a very small rest More

Org Clock Watch Micro Rest P 
   non-nil means will send micro rest alarm, nil will disable it

Org Clock Watch Micro Rest Sound 
   The path to a sound file that´s to be played when need micro rest.
```
>     Ctrl-g not working, keyboard and mouse not working , only by force kill the emacs app!
This should be caused by dbus issue, you need install emacs with dbus support

**Comment by wztdream** [comment]
Or maybe in windows you only need to install dbus, as the doc for in Elisp info only mentioned need compile emacs with dbus support for POSIX host, which means linux like os. So I guess maybe you only need install dbus on windows10, I am not sure, you can do some home work and have a try.
[this link](https://www.freedesktop.org/wiki/Software/dbus/#windowsport) maybe useful for you, it says dbus support windows.
